### ISSUE TITLE
NetCDF does support projections

### ISSUE THREAD

**Issue by scw** [tmcw/simpleopendata#17]
The current section mentions using NetCDF exclusively for non-geographical array data, but wanted to mention that the base spec (and particularly, with the CF conventions), NetCDF supports a [handful of the most common projections](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/v4.2/javadoc/ucar/unidata/geoloc/projection/package-summary.html) and should be considered fair game for interchange of geographic data -- it's widely used in the oceanographic and climatic worlds without issue for interchanging multidimensional sets of geographically referenced data.

**Comment by tmcw** [comment]
> For larger raster datasets and non-geographical array data, NetCDF is another good choice with wide support.

I wrote & parse this sentence with an _and_, so it covers both "larger raster datasets" which are geographical as implied by the rest of the paragraph _and_ non-geographical raster data.

**Comment by scw** [comment]
Yeah, I misinterpreted. :+1:
