### ISSUE TITLE
Please consider adding this GIS open format

### ISSUE THREAD

**Issue by Jelfff** [tmcw/simpleopendata#21]
I read well-written and upbeat blurb at http://simpleopendata.com/
and have a comment from the down-in-the-weeds perspective of a software developer working with the google map API and open geospatial data.

The current version of simpleopendata neglects to mention the most common open format that  government agencies at all levels already use for open geospatial data.  All kinds of agencies are already publishing a staggering quantity of open data in this format.  Although there might be a better name, I will call this format “ArcGIS services on a *public facing* server”.

This is an open format for two reasons.

First, anyone can use the ESRI REST API to formulate an http command that can be entered into a browser and download data in various formats.  This API is powerful and includes SQL ‘where’ capability.
Here is the documentation for ‘query’ which will let you download data as json or kmz files:  http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Query_Map_Service_Layer/02r3000000p1000000/
Yes, there is a learning curve.

Second, anyone with GIS client software can likely read this data.

Data in this format is arranged in an inverted tree just like the folders and files on a PC.  What corresponds to the ‘root’ folder is called an “endpoint” and is a url.  Here is an example of an endpoint from the USGS: http://hdds.usgs.gov/ArcGIS/rest/services
You can drill down on those links and fairly quickly find metadata about each layer of data available via this endpoint.  Note - By definition, an ArcGIS endpoint url always ends in “rest/services”.

Recommendation: Please consider adding something like “ArcGIS services on a *public facing* server” to the list of open data formats.

Three final points.

First, I say *public facing* server since it is also possible for an agency to have data in the exact same data format on a non-public server.  An example is the national park service.  They have what they call “atlas” data for many national parks on non-public ArcGIS servers.  Why they refuse to disclose geospatial data for picnic areas etc is a mystery to me.

Second, agencies need to publish their ArcGIS endpoints.  Most do not.  Most agencies also do not place their ArcGIS endpoints on data.gov.  And to complicate matters, data.gov does not seem to provide a way to search just for ArcGIS endpoints.  Life would be so much easier for open data advocates if there was an easy way to find the 4 or 5 ArcGIS endpoints used by an agency.

Third, with some creative google searching I have complied a list of a bunch of ArcGIS endpoints for federal agencies.  That list is at:
http://www.mappingsupport.com/p/gmap4_gis_more_help.html#source_federal

And here is a very small example of maps that can be produced with the existing open federal ArcGIS data (scroll down for the links).  To learn how to turn ArcGIS layers on/off, click “About this map” in the upper left corner of any map.
http://www.propertylinemaps.com/p/public_land_map.html

Joseph Elfelt
Redmond, WA

**Comment by tmcw** [comment]
Thanks for the note, Joseph. Luckily Esri is doing a lot in terms of open data, and their open data server supports GeoJSON, KML, and Shapefiles, which are already mentioned in the guide. I'd rather stay away from endorsing specific technology and err towards recommending file standards, but it's noted that this is a useful technology for publishing federal data.
